#-------------------------------------------------
#
# Project created by QtCreator 2016-10-04T17:33:55
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = CourveFever
TEMPLATE = app


SOURCES += main.cpp\
        mainwindow.cpp \
    player.cpp \
    circle.cpp \
    vector.cpp \
    point.cpp \
    gameitem.cpp \
    bonus.cpp \
    field.cpp \
    eigen/bench/btl/data/mean.cxx \
    eigen/bench/btl/data/regularize.cxx \
    eigen/bench/btl/data/smooth.cxx \
    eigen/bench/btl/libs/BLAS/main.cpp \
    eigen/bench/btl/libs/blitz/btl_blitz.cpp \
    eigen/bench/btl/libs/blitz/btl_tiny_blitz.cpp \
    eigen/bench/btl/libs/eigen2/btl_tiny_eigen2.cpp \
    eigen/bench/btl/libs/eigen2/main_adv.cpp \
    eigen/bench/btl/libs/eigen2/main_linear.cpp \
    eigen/bench/btl/libs/eigen2/main_matmat.cpp \
    eigen/bench/btl/libs/eigen2/main_vecmat.cpp \
    eigen/bench/btl/libs/eigen3/btl_tiny_eigen3.cpp \
    eigen/bench/btl/libs/eigen3/main_adv.cpp \
    eigen/bench/btl/libs/eigen3/main_linear.cpp \
    eigen/bench/btl/libs/eigen3/main_matmat.cpp \
    eigen/bench/btl/libs/eigen3/main_vecmat.cpp \
    eigen/bench/btl/libs/gmm/main.cpp \
    eigen/bench/btl/libs/mtl4/main.cpp \
    eigen/bench/btl/libs/STL/main.cpp \
    eigen/bench/btl/libs/tvmet/main.cpp \
    eigen/bench/btl/libs/ublas/main.cpp \
    eigen/bench/spbench/sp_solver.cpp \
    eigen/bench/spbench/spbenchsolver.cpp \
    eigen/bench/spbench/test_sparseLU.cpp \
    eigen/bench/basicbenchmark.cpp \
    eigen/bench/bench_gemm.cpp \
    eigen/bench/bench_norm.cpp \
    eigen/bench/bench_reverse.cpp \
    eigen/bench/bench_sum.cpp \
    eigen/bench/benchBlasGemm.cpp \
    eigen/bench/benchCholesky.cpp \
    eigen/bench/benchEigenSolver.cpp \
    eigen/bench/benchFFT.cpp \
    eigen/bench/benchGeometry.cpp \
    eigen/bench/benchmark.cpp \
    eigen/bench/benchmarkSlice.cpp \
    eigen/bench/benchmarkX.cpp \
    eigen/bench/benchmarkXcwise.cpp \
    eigen/bench/benchVecAdd.cpp \
    eigen/bench/check_cache_queries.cpp \
    eigen/bench/eig33.cpp \
    eigen/bench/geometry.cpp \
    eigen/bench/product_threshold.cpp \
    eigen/bench/quat_slerp.cpp \
    eigen/bench/quatmul.cpp \
    eigen/bench/sparse_cholesky.cpp \
    eigen/bench/sparse_dense_product.cpp \
    eigen/bench/sparse_lu.cpp \
    eigen/bench/sparse_product.cpp \
    eigen/bench/sparse_randomsetter.cpp \
    eigen/bench/sparse_setter.cpp \
    eigen/bench/sparse_transpose.cpp \
    eigen/bench/sparse_trisolver.cpp \
    eigen/bench/spmv.cpp \
    eigen/bench/vdw_new.cpp \
    eigen/blas/complex_double.cpp \
    eigen/blas/complex_single.cpp \
    eigen/blas/double.cpp \
    eigen/blas/single.cpp \
    eigen/blas/xerbla.cpp \
    eigen/demos/mandelbrot/mandelbrot.cpp \
    eigen/demos/mix_eigen_and_c/binary_library.cpp \
    eigen/demos/opengl/camera.cpp \
    eigen/demos/opengl/gpuhelper.cpp \
    eigen/demos/opengl/icosphere.cpp \
    eigen/demos/opengl/quaternion_demo.cpp \
    eigen/demos/opengl/trackball.cpp \
    eigen/doc/examples/class_Block.cpp \
    eigen/doc/examples/class_CwiseBinaryOp.cpp \
    eigen/doc/examples/class_CwiseUnaryOp.cpp \
    eigen/doc/examples/class_CwiseUnaryOp_ptrfun.cpp \
    eigen/doc/examples/class_FixedBlock.cpp \
    eigen/doc/examples/class_FixedVectorBlock.cpp \
    eigen/doc/examples/class_VectorBlock.cpp \
    eigen/doc/examples/DenseBase_middleCols_int.cpp \
    eigen/doc/examples/DenseBase_middleRows_int.cpp \
    eigen/doc/examples/DenseBase_template_int_middleCols.cpp \
    eigen/doc/examples/DenseBase_template_int_middleRows.cpp \
    eigen/doc/examples/function_taking_eigenbase.cpp \
    eigen/doc/examples/function_taking_ref.cpp \
    eigen/doc/examples/MatrixBase_cwise_const.cpp \
    eigen/doc/examples/matrixfree_cg.cpp \
    eigen/doc/examples/QuickStart_example.cpp \
    eigen/doc/examples/QuickStart_example2_dynamic.cpp \
    eigen/doc/examples/QuickStart_example2_fixed.cpp \
    eigen/doc/examples/TemplateKeyword_flexible.cpp \
    eigen/doc/examples/TemplateKeyword_simple.cpp \
    eigen/doc/examples/tut_arithmetic_add_sub.cpp \
    eigen/doc/examples/tut_arithmetic_dot_cross.cpp \
    eigen/doc/examples/tut_arithmetic_matrix_mul.cpp \
    eigen/doc/examples/tut_arithmetic_redux_basic.cpp \
    eigen/doc/examples/tut_arithmetic_scalar_mul_div.cpp \
    eigen/doc/examples/tut_matrix_coefficient_accessors.cpp \
    eigen/doc/examples/tut_matrix_resize.cpp \
    eigen/doc/examples/tut_matrix_resize_fixed_size.cpp \
    eigen/doc/examples/Tutorial_ArrayClass_accessors.cpp \
    eigen/doc/examples/Tutorial_ArrayClass_addition.cpp \
    eigen/doc/examples/Tutorial_ArrayClass_cwise_other.cpp \
    eigen/doc/examples/Tutorial_ArrayClass_interop.cpp \
    eigen/doc/examples/Tutorial_ArrayClass_interop_matrix.cpp \
    eigen/doc/examples/Tutorial_ArrayClass_mult.cpp \
    eigen/doc/examples/Tutorial_BlockOperations_block_assignment.cpp \
    eigen/doc/examples/Tutorial_BlockOperations_colrow.cpp \
    eigen/doc/examples/Tutorial_BlockOperations_corner.cpp \
    eigen/doc/examples/Tutorial_BlockOperations_print_block.cpp \
    eigen/doc/examples/Tutorial_BlockOperations_vector.cpp \
    eigen/doc/examples/Tutorial_PartialLU_solve.cpp \
    eigen/doc/examples/Tutorial_ReductionsVisitorsBroadcasting_broadcast_1nn.cpp \
    eigen/doc/examples/Tutorial_ReductionsVisitorsBroadcasting_broadcast_simple.cpp \
    eigen/doc/examples/Tutorial_ReductionsVisitorsBroadcasting_broadcast_simple_rowwise.cpp \
    eigen/doc/examples/Tutorial_ReductionsVisitorsBroadcasting_colwise.cpp \
    eigen/doc/examples/Tutorial_ReductionsVisitorsBroadcasting_maxnorm.cpp \
    eigen/doc/examples/Tutorial_ReductionsVisitorsBroadcasting_reductions_bool.cpp \
    eigen/doc/examples/Tutorial_ReductionsVisitorsBroadcasting_reductions_norm.cpp \
    eigen/doc/examples/Tutorial_ReductionsVisitorsBroadcasting_rowwise.cpp \
    eigen/doc/examples/Tutorial_ReductionsVisitorsBroadcasting_visitors.cpp \
    eigen/doc/examples/Tutorial_simple_example_dynamic_size.cpp \
    eigen/doc/examples/Tutorial_simple_example_fixed_size.cpp \
    eigen/doc/examples/TutorialLinAlgComputeTwice.cpp \
    eigen/doc/examples/TutorialLinAlgExComputeSolveError.cpp \
    eigen/doc/examples/TutorialLinAlgExSolveColPivHouseholderQR.cpp \
    eigen/doc/examples/TutorialLinAlgExSolveLDLT.cpp \
    eigen/doc/examples/TutorialLinAlgInverseDeterminant.cpp \
    eigen/doc/examples/TutorialLinAlgRankRevealing.cpp \
    eigen/doc/examples/TutorialLinAlgSelfAdjointEigenSolver.cpp \
    eigen/doc/examples/TutorialLinAlgSetThreshold.cpp \
    eigen/doc/examples/TutorialLinAlgSVDSolve.cpp \
    eigen/doc/snippets/AngleAxis_mimic_euler.cpp \
    eigen/doc/snippets/class_FullPivLU.cpp \
    eigen/doc/snippets/ColPivHouseholderQR_solve.cpp \
    eigen/doc/snippets/ComplexEigenSolver_compute.cpp \
    eigen/doc/snippets/ComplexEigenSolver_eigenvalues.cpp \
    eigen/doc/snippets/ComplexEigenSolver_eigenvectors.cpp \
    eigen/doc/snippets/ComplexSchur_compute.cpp \
    eigen/doc/snippets/ComplexSchur_matrixT.cpp \
    eigen/doc/snippets/ComplexSchur_matrixU.cpp \
    eigen/doc/snippets/Cwise_abs.cpp \
    eigen/doc/snippets/Cwise_abs2.cpp \
    eigen/doc/snippets/Cwise_acos.cpp \
    eigen/doc/snippets/Cwise_asin.cpp \
    eigen/doc/snippets/Cwise_boolean_and.cpp \
    eigen/doc/snippets/Cwise_boolean_or.cpp \
    eigen/doc/snippets/Cwise_cos.cpp \
    eigen/doc/snippets/Cwise_cube.cpp \
    eigen/doc/snippets/Cwise_equal_equal.cpp \
    eigen/doc/snippets/Cwise_exp.cpp \
    eigen/doc/snippets/Cwise_greater.cpp \
    eigen/doc/snippets/Cwise_greater_equal.cpp \
    eigen/doc/snippets/Cwise_inverse.cpp \
    eigen/doc/snippets/Cwise_less.cpp \
    eigen/doc/snippets/Cwise_less_equal.cpp \
    eigen/doc/snippets/Cwise_log.cpp \
    eigen/doc/snippets/Cwise_max.cpp \
    eigen/doc/snippets/Cwise_min.cpp \
    eigen/doc/snippets/Cwise_minus.cpp \
    eigen/doc/snippets/Cwise_minus_equal.cpp \
    eigen/doc/snippets/Cwise_not_equal.cpp \
    eigen/doc/snippets/Cwise_plus.cpp \
    eigen/doc/snippets/Cwise_plus_equal.cpp \
    eigen/doc/snippets/Cwise_pow.cpp \
    eigen/doc/snippets/Cwise_product.cpp \
    eigen/doc/snippets/Cwise_quotient.cpp \
    eigen/doc/snippets/Cwise_sin.cpp \
    eigen/doc/snippets/Cwise_slash_equal.cpp \
    eigen/doc/snippets/Cwise_sqrt.cpp \
    eigen/doc/snippets/Cwise_square.cpp \
    eigen/doc/snippets/Cwise_tan.cpp \
    eigen/doc/snippets/Cwise_times_equal.cpp \
    eigen/doc/snippets/DenseBase_LinSpaced.cpp \
    eigen/doc/snippets/DenseBase_LinSpaced_seq.cpp \
    eigen/doc/snippets/DenseBase_setLinSpaced.cpp \
    eigen/doc/snippets/DirectionWise_replicate.cpp \
    eigen/doc/snippets/DirectionWise_replicate_int.cpp \
    eigen/doc/snippets/EigenSolver_compute.cpp \
    eigen/doc/snippets/EigenSolver_EigenSolver_MatrixType.cpp \
    eigen/doc/snippets/EigenSolver_eigenvalues.cpp \
    eigen/doc/snippets/EigenSolver_eigenvectors.cpp \
    eigen/doc/snippets/EigenSolver_pseudoEigenvectors.cpp \
    eigen/doc/snippets/FullPivHouseholderQR_solve.cpp \
    eigen/doc/snippets/FullPivLU_image.cpp \
    eigen/doc/snippets/FullPivLU_kernel.cpp \
    eigen/doc/snippets/FullPivLU_solve.cpp \
    eigen/doc/snippets/GeneralizedEigenSolver.cpp \
    eigen/doc/snippets/HessenbergDecomposition_compute.cpp \
    eigen/doc/snippets/HessenbergDecomposition_matrixH.cpp \
    eigen/doc/snippets/HessenbergDecomposition_packedMatrix.cpp \
    eigen/doc/snippets/HouseholderQR_householderQ.cpp \
    eigen/doc/snippets/HouseholderQR_solve.cpp \
    eigen/doc/snippets/HouseholderSequence_HouseholderSequence.cpp \
    eigen/doc/snippets/IOFormat.cpp \
    eigen/doc/snippets/Jacobi_makeGivens.cpp \
    eigen/doc/snippets/Jacobi_makeJacobi.cpp \
    eigen/doc/snippets/JacobiSVD_basic.cpp \
    eigen/doc/snippets/LLT_example.cpp \
    eigen/doc/snippets/LLT_solve.cpp \
    eigen/doc/snippets/Map_general_stride.cpp \
    eigen/doc/snippets/Map_inner_stride.cpp \
    eigen/doc/snippets/Map_outer_stride.cpp \
    eigen/doc/snippets/Map_placement_new.cpp \
    eigen/doc/snippets/Map_simple.cpp \
    eigen/doc/snippets/Matrix_resize_int.cpp \
    eigen/doc/snippets/Matrix_resize_int_int.cpp \
    eigen/doc/snippets/Matrix_resize_int_NoChange.cpp \
    eigen/doc/snippets/Matrix_resize_NoChange_int.cpp \
    eigen/doc/snippets/Matrix_setConstant_int.cpp \
    eigen/doc/snippets/Matrix_setConstant_int_int.cpp \
    eigen/doc/snippets/Matrix_setIdentity_int_int.cpp \
    eigen/doc/snippets/Matrix_setOnes_int.cpp \
    eigen/doc/snippets/Matrix_setOnes_int_int.cpp \
    eigen/doc/snippets/Matrix_setRandom_int.cpp \
    eigen/doc/snippets/Matrix_setRandom_int_int.cpp \
    eigen/doc/snippets/Matrix_setZero_int.cpp \
    eigen/doc/snippets/Matrix_setZero_int_int.cpp \
    eigen/doc/snippets/MatrixBase_adjoint.cpp \
    eigen/doc/snippets/MatrixBase_all.cpp \
    eigen/doc/snippets/MatrixBase_applyOnTheLeft.cpp \
    eigen/doc/snippets/MatrixBase_applyOnTheRight.cpp \
    eigen/doc/snippets/MatrixBase_array.cpp \
    eigen/doc/snippets/MatrixBase_array_const.cpp \
    eigen/doc/snippets/MatrixBase_asDiagonal.cpp \
    eigen/doc/snippets/MatrixBase_block_int_int.cpp \
    eigen/doc/snippets/MatrixBase_block_int_int_int_int.cpp \
    eigen/doc/snippets/MatrixBase_bottomLeftCorner_int_int.cpp \
    eigen/doc/snippets/MatrixBase_bottomRightCorner_int_int.cpp \
    eigen/doc/snippets/MatrixBase_bottomRows_int.cpp \
    eigen/doc/snippets/MatrixBase_cast.cpp \
    eigen/doc/snippets/MatrixBase_col.cpp \
    eigen/doc/snippets/MatrixBase_colwise.cpp \
    eigen/doc/snippets/MatrixBase_computeInverseAndDetWithCheck.cpp \
    eigen/doc/snippets/MatrixBase_computeInverseWithCheck.cpp \
    eigen/doc/snippets/MatrixBase_cwiseAbs.cpp \
    eigen/doc/snippets/MatrixBase_cwiseAbs2.cpp \
    eigen/doc/snippets/MatrixBase_cwiseEqual.cpp \
    eigen/doc/snippets/MatrixBase_cwiseInverse.cpp \
    eigen/doc/snippets/MatrixBase_cwiseMax.cpp \
    eigen/doc/snippets/MatrixBase_cwiseMin.cpp \
    eigen/doc/snippets/MatrixBase_cwiseNotEqual.cpp \
    eigen/doc/snippets/MatrixBase_cwiseProduct.cpp \
    eigen/doc/snippets/MatrixBase_cwiseQuotient.cpp \
    eigen/doc/snippets/MatrixBase_cwiseSqrt.cpp \
    eigen/doc/snippets/MatrixBase_diagonal.cpp \
    eigen/doc/snippets/MatrixBase_diagonal_int.cpp \
    eigen/doc/snippets/MatrixBase_diagonal_template_int.cpp \
    eigen/doc/snippets/MatrixBase_eigenvalues.cpp \
    eigen/doc/snippets/MatrixBase_end_int.cpp \
    eigen/doc/snippets/MatrixBase_eval.cpp \
    eigen/doc/snippets/MatrixBase_extract.cpp \
    eigen/doc/snippets/MatrixBase_fixedBlock_int_int.cpp \
    eigen/doc/snippets/MatrixBase_identity.cpp \
    eigen/doc/snippets/MatrixBase_identity_int_int.cpp \
    eigen/doc/snippets/MatrixBase_inverse.cpp \
    eigen/doc/snippets/MatrixBase_isDiagonal.cpp \
    eigen/doc/snippets/MatrixBase_isIdentity.cpp \
    eigen/doc/snippets/MatrixBase_isOnes.cpp \
    eigen/doc/snippets/MatrixBase_isOrthogonal.cpp \
    eigen/doc/snippets/MatrixBase_isUnitary.cpp \
    eigen/doc/snippets/MatrixBase_isZero.cpp \
    eigen/doc/snippets/MatrixBase_leftCols_int.cpp \
    eigen/doc/snippets/MatrixBase_marked.cpp \
    eigen/doc/snippets/MatrixBase_noalias.cpp \
    eigen/doc/snippets/MatrixBase_ones.cpp \
    eigen/doc/snippets/MatrixBase_ones_int.cpp \
    eigen/doc/snippets/MatrixBase_ones_int_int.cpp \
    eigen/doc/snippets/MatrixBase_operatorNorm.cpp \
    eigen/doc/snippets/MatrixBase_part.cpp \
    eigen/doc/snippets/MatrixBase_prod.cpp \
    eigen/doc/snippets/MatrixBase_random.cpp \
    eigen/doc/snippets/MatrixBase_random_int.cpp \
    eigen/doc/snippets/MatrixBase_random_int_int.cpp \
    eigen/doc/snippets/MatrixBase_replicate.cpp \
    eigen/doc/snippets/MatrixBase_replicate_int_int.cpp \
    eigen/doc/snippets/MatrixBase_reverse.cpp \
    eigen/doc/snippets/MatrixBase_rightCols_int.cpp \
    eigen/doc/snippets/MatrixBase_row.cpp \
    eigen/doc/snippets/MatrixBase_rowwise.cpp \
    eigen/doc/snippets/MatrixBase_segment_int_int.cpp \
    eigen/doc/snippets/MatrixBase_select.cpp \
    eigen/doc/snippets/MatrixBase_set.cpp \
    eigen/doc/snippets/MatrixBase_setIdentity.cpp \
    eigen/doc/snippets/MatrixBase_setOnes.cpp \
    eigen/doc/snippets/MatrixBase_setRandom.cpp \
    eigen/doc/snippets/MatrixBase_setZero.cpp \
    eigen/doc/snippets/MatrixBase_start_int.cpp \
    eigen/doc/snippets/MatrixBase_template_int_bottomRows.cpp \
    eigen/doc/snippets/MatrixBase_template_int_end.cpp \
    eigen/doc/snippets/MatrixBase_template_int_int_block_int_int_int_int.cpp \
    eigen/doc/snippets/MatrixBase_template_int_int_bottomLeftCorner.cpp \
    eigen/doc/snippets/MatrixBase_template_int_int_bottomLeftCorner_int_int.cpp \
    eigen/doc/snippets/MatrixBase_template_int_int_bottomRightCorner.cpp \
    eigen/doc/snippets/MatrixBase_template_int_int_bottomRightCorner_int_int.cpp \
    eigen/doc/snippets/MatrixBase_template_int_int_topLeftCorner.cpp \
    eigen/doc/snippets/MatrixBase_template_int_int_topLeftCorner_int_int.cpp \
    eigen/doc/snippets/MatrixBase_template_int_int_topRightCorner.cpp \
    eigen/doc/snippets/MatrixBase_template_int_int_topRightCorner_int_int.cpp \
    eigen/doc/snippets/MatrixBase_template_int_leftCols.cpp \
    eigen/doc/snippets/MatrixBase_template_int_rightCols.cpp \
    eigen/doc/snippets/MatrixBase_template_int_segment.cpp \
    eigen/doc/snippets/MatrixBase_template_int_start.cpp \
    eigen/doc/snippets/MatrixBase_template_int_topRows.cpp \
    eigen/doc/snippets/MatrixBase_topLeftCorner_int_int.cpp \
    eigen/doc/snippets/MatrixBase_topRightCorner_int_int.cpp \
    eigen/doc/snippets/MatrixBase_topRows_int.cpp \
    eigen/doc/snippets/MatrixBase_transpose.cpp \
    eigen/doc/snippets/MatrixBase_zero.cpp \
    eigen/doc/snippets/MatrixBase_zero_int.cpp \
    eigen/doc/snippets/MatrixBase_zero_int_int.cpp \
    eigen/doc/snippets/PartialPivLU_solve.cpp \
    eigen/doc/snippets/PartialRedux_count.cpp \
    eigen/doc/snippets/PartialRedux_maxCoeff.cpp \
    eigen/doc/snippets/PartialRedux_minCoeff.cpp \
    eigen/doc/snippets/PartialRedux_norm.cpp \
    eigen/doc/snippets/PartialRedux_prod.cpp \
    eigen/doc/snippets/PartialRedux_squaredNorm.cpp \
    eigen/doc/snippets/PartialRedux_sum.cpp \
    eigen/doc/snippets/RealQZ_compute.cpp \
    eigen/doc/snippets/RealSchur_compute.cpp \
    eigen/doc/snippets/RealSchur_RealSchur_MatrixType.cpp \
    eigen/doc/snippets/SelfAdjointEigenSolver_compute_MatrixType.cpp \
    eigen/doc/snippets/SelfAdjointEigenSolver_compute_MatrixType2.cpp \
    eigen/doc/snippets/SelfAdjointEigenSolver_eigenvalues.cpp \
    eigen/doc/snippets/SelfAdjointEigenSolver_eigenvectors.cpp \
    eigen/doc/snippets/SelfAdjointEigenSolver_operatorInverseSqrt.cpp \
    eigen/doc/snippets/SelfAdjointEigenSolver_operatorSqrt.cpp \
    eigen/doc/snippets/SelfAdjointEigenSolver_SelfAdjointEigenSolver.cpp \
    eigen/doc/snippets/SelfAdjointEigenSolver_SelfAdjointEigenSolver_MatrixType.cpp \
    eigen/doc/snippets/SelfAdjointEigenSolver_SelfAdjointEigenSolver_MatrixType2.cpp \
    eigen/doc/snippets/SelfAdjointView_eigenvalues.cpp \
    eigen/doc/snippets/SelfAdjointView_operatorNorm.cpp \
    eigen/doc/snippets/TopicAliasing_block.cpp \
    eigen/doc/snippets/TopicAliasing_block_correct.cpp \
    eigen/doc/snippets/TopicAliasing_cwise.cpp \
    eigen/doc/snippets/TopicAliasing_mult1.cpp \
    eigen/doc/snippets/TopicAliasing_mult2.cpp \
    eigen/doc/snippets/TopicAliasing_mult3.cpp \
    eigen/doc/snippets/TopicStorageOrders_example.cpp \
    eigen/doc/snippets/Tridiagonalization_compute.cpp \
    eigen/doc/snippets/Tridiagonalization_decomposeInPlace.cpp \
    eigen/doc/snippets/Tridiagonalization_diagonal.cpp \
    eigen/doc/snippets/Tridiagonalization_householderCoefficients.cpp \
    eigen/doc/snippets/Tridiagonalization_packedMatrix.cpp \
    eigen/doc/snippets/Tridiagonalization_Tridiagonalization_MatrixType.cpp \
    eigen/doc/snippets/tut_arithmetic_redux_minmax.cpp \
    eigen/doc/snippets/tut_arithmetic_transpose_aliasing.cpp \
    eigen/doc/snippets/tut_arithmetic_transpose_conjugate.cpp \
    eigen/doc/snippets/tut_arithmetic_transpose_inplace.cpp \
    eigen/doc/snippets/tut_matrix_assignment_resizing.cpp \
    eigen/doc/snippets/Tutorial_AdvancedInitialization_Block.cpp \
    eigen/doc/snippets/Tutorial_AdvancedInitialization_CommaTemporary.cpp \
    eigen/doc/snippets/Tutorial_AdvancedInitialization_Join.cpp \
    eigen/doc/snippets/Tutorial_AdvancedInitialization_LinSpaced.cpp \
    eigen/doc/snippets/Tutorial_AdvancedInitialization_ThreeWays.cpp \
    eigen/doc/snippets/Tutorial_AdvancedInitialization_Zero.cpp \
    eigen/doc/snippets/Tutorial_commainit_01.cpp \
    eigen/doc/snippets/Tutorial_commainit_01b.cpp \
    eigen/doc/snippets/Tutorial_commainit_02.cpp \
    eigen/doc/snippets/Tutorial_Map_rowmajor.cpp \
    eigen/doc/snippets/Tutorial_Map_using.cpp \
    eigen/doc/snippets/Tutorial_solve_matrix_inverse.cpp \
    eigen/doc/snippets/Tutorial_solve_multiple_rhs.cpp \
    eigen/doc/snippets/Tutorial_solve_reuse_decomposition.cpp \
    eigen/doc/snippets/Tutorial_solve_singular.cpp \
    eigen/doc/snippets/Tutorial_solve_triangular.cpp \
    eigen/doc/snippets/Tutorial_solve_triangular_inplace.cpp \
    eigen/doc/snippets/Vectorwise_reverse.cpp \
    eigen/doc/special_examples/Tutorial_sparse_example.cpp \
    eigen/doc/special_examples/Tutorial_sparse_example_details.cpp \
    eigen/doc/tutorial.cpp \
    eigen/failtest/block_nonconst_ctor_on_const_xpr_0.cpp \
    eigen/failtest/block_nonconst_ctor_on_const_xpr_1.cpp \
    eigen/failtest/block_nonconst_ctor_on_const_xpr_2.cpp \
    eigen/failtest/block_on_const_type_actually_const_0.cpp \
    eigen/failtest/block_on_const_type_actually_const_1.cpp \
    eigen/failtest/colpivqr_int.cpp \
    eigen/failtest/const_qualified_block_method_retval_0.cpp \
    eigen/failtest/const_qualified_block_method_retval_1.cpp \
    eigen/failtest/const_qualified_diagonal_method_retval.cpp \
    eigen/failtest/const_qualified_transpose_method_retval.cpp \
    eigen/failtest/diagonal_nonconst_ctor_on_const_xpr.cpp \
    eigen/failtest/diagonal_on_const_type_actually_const.cpp \
    eigen/failtest/eigensolver_cplx.cpp \
    eigen/failtest/eigensolver_int.cpp \
    eigen/failtest/failtest_sanity_check.cpp \
    eigen/failtest/fullpivlu_int.cpp \
    eigen/failtest/fullpivqr_int.cpp \
    eigen/failtest/jacobisvd_int.cpp \
    eigen/failtest/ldlt_int.cpp \
    eigen/failtest/llt_int.cpp \
    eigen/failtest/map_nonconst_ctor_on_const_ptr_0.cpp \
    eigen/failtest/map_nonconst_ctor_on_const_ptr_1.cpp \
    eigen/failtest/map_nonconst_ctor_on_const_ptr_2.cpp \
    eigen/failtest/map_nonconst_ctor_on_const_ptr_3.cpp \
    eigen/failtest/map_nonconst_ctor_on_const_ptr_4.cpp \
    eigen/failtest/map_on_const_type_actually_const_0.cpp \
    eigen/failtest/map_on_const_type_actually_const_1.cpp \
    eigen/failtest/partialpivlu_int.cpp \
    eigen/failtest/qr_int.cpp \
    eigen/failtest/ref_1.cpp \
    eigen/failtest/ref_2.cpp \
    eigen/failtest/ref_3.cpp \
    eigen/failtest/ref_4.cpp \
    eigen/failtest/ref_5.cpp \
    eigen/failtest/transpose_nonconst_ctor_on_const_xpr.cpp \
    eigen/failtest/transpose_on_const_type_actually_const.cpp \
    eigen/lapack/cholesky.cpp \
    eigen/lapack/complex_double.cpp \
    eigen/lapack/complex_single.cpp \
    eigen/lapack/double.cpp \
    eigen/lapack/eigenvalues.cpp \
    eigen/lapack/lu.cpp \
    eigen/lapack/single.cpp \
    eigen/scripts/eigen_gen_credits.cpp \
    eigen/test/eigen2/eigen2_adjoint.cpp \
    eigen/test/eigen2/eigen2_alignedbox.cpp \
    eigen/test/eigen2/eigen2_array.cpp \
    eigen/test/eigen2/eigen2_basicstuff.cpp \
    eigen/test/eigen2/eigen2_bug_132.cpp \
    eigen/test/eigen2/eigen2_cholesky.cpp \
    eigen/test/eigen2/eigen2_commainitializer.cpp \
    eigen/test/eigen2/eigen2_cwiseop.cpp \
    eigen/test/eigen2/eigen2_determinant.cpp \
    eigen/test/eigen2/eigen2_dynalloc.cpp \
    eigen/test/eigen2/eigen2_eigensolver.cpp \
    eigen/test/eigen2/eigen2_first_aligned.cpp \
    eigen/test/eigen2/eigen2_geometry.cpp \
    eigen/test/eigen2/eigen2_geometry_with_eigen2_prefix.cpp \
    eigen/test/eigen2/eigen2_hyperplane.cpp \
    eigen/test/eigen2/eigen2_inverse.cpp \
    eigen/test/eigen2/eigen2_linearstructure.cpp \
    eigen/test/eigen2/eigen2_lu.cpp \
    eigen/test/eigen2/eigen2_map.cpp \
    eigen/test/eigen2/eigen2_meta.cpp \
    eigen/test/eigen2/eigen2_miscmatrices.cpp \
    eigen/test/eigen2/eigen2_mixingtypes.cpp \
    eigen/test/eigen2/eigen2_newstdvector.cpp \
    eigen/test/eigen2/eigen2_nomalloc.cpp \
    eigen/test/eigen2/eigen2_packetmath.cpp \
    eigen/test/eigen2/eigen2_parametrizedline.cpp \
    eigen/test/eigen2/eigen2_prec_inverse_4x4.cpp \
    eigen/test/eigen2/eigen2_product_large.cpp \
    eigen/test/eigen2/eigen2_product_small.cpp \
    eigen/test/eigen2/eigen2_qr.cpp \
    eigen/test/eigen2/eigen2_qtvector.cpp \
    eigen/test/eigen2/eigen2_regression.cpp \
    eigen/test/eigen2/eigen2_sizeof.cpp \
    eigen/test/eigen2/eigen2_smallvectors.cpp \
    eigen/test/eigen2/eigen2_sparse_basic.cpp \
    eigen/test/eigen2/eigen2_sparse_product.cpp \
    eigen/test/eigen2/eigen2_sparse_solvers.cpp \
    eigen/test/eigen2/eigen2_sparse_vector.cpp \
    eigen/test/eigen2/eigen2_stdvector.cpp \
    eigen/test/eigen2/eigen2_submatrices.cpp \
    eigen/test/eigen2/eigen2_sum.cpp \
    eigen/test/eigen2/eigen2_svd.cpp \
    eigen/test/eigen2/eigen2_swap.cpp \
    eigen/test/eigen2/eigen2_triangular.cpp \
    eigen/test/eigen2/eigen2_unalignedassert.cpp \
    eigen/test/eigen2/eigen2_visitor.cpp \
    eigen/test/adjoint.cpp \
    eigen/test/array.cpp \
    eigen/test/array_for_matrix.cpp \
    eigen/test/array_replicate.cpp \
    eigen/test/array_reverse.cpp \
    eigen/test/bandmatrix.cpp \
    eigen/test/basicstuff.cpp \
    eigen/test/bicgstab.cpp \
    eigen/test/block.cpp \
    eigen/test/cholesky.cpp \
    eigen/test/cholmod_support.cpp \
    eigen/test/commainitializer.cpp \
    eigen/test/conjugate_gradient.cpp \
    eigen/test/conservative_resize.cpp \
    eigen/test/corners.cpp \
    eigen/test/cwiseop.cpp \
    eigen/test/denseLM.cpp \
    eigen/test/determinant.cpp \
    eigen/test/diagonal.cpp \
    eigen/test/diagonalmatrices.cpp \
    eigen/test/dontalign.cpp \
    eigen/test/dynalloc.cpp \
    eigen/test/eigen2support.cpp \
    eigen/test/eigensolver_complex.cpp \
    eigen/test/eigensolver_generalized_real.cpp \
    eigen/test/eigensolver_generic.cpp \
    eigen/test/eigensolver_selfadjoint.cpp \
    eigen/test/exceptions.cpp \
    eigen/test/first_aligned.cpp \
    eigen/test/geo_alignedbox.cpp \
    eigen/test/geo_eulerangles.cpp \
    eigen/test/geo_homogeneous.cpp \
    eigen/test/geo_hyperplane.cpp \
    eigen/test/geo_orthomethods.cpp \
    eigen/test/geo_parametrizedline.cpp \
    eigen/test/geo_quaternion.cpp \
    eigen/test/geo_transformations.cpp \
    eigen/test/hessenberg.cpp \
    eigen/test/householder.cpp \
    eigen/test/integer_types.cpp \
    eigen/test/inverse.cpp \
    eigen/test/jacobi.cpp \
    eigen/test/jacobisvd.cpp \
    eigen/test/linearstructure.cpp \
    eigen/test/lu.cpp \
    eigen/test/mapped_matrix.cpp \
    eigen/test/mapstaticmethods.cpp \
    eigen/test/mapstride.cpp \
    eigen/test/meta.cpp \
    eigen/test/metis_support.cpp \
    eigen/test/miscmatrices.cpp \
    eigen/test/mixingtypes.cpp \
    eigen/test/mpl2only.cpp \
    eigen/test/nesting_ops.cpp \
    eigen/test/nomalloc.cpp \
    eigen/test/nullary.cpp \
    eigen/test/packetmath.cpp \
    eigen/test/pardiso_support.cpp \
    eigen/test/pastix_support.cpp \
    eigen/test/permutationmatrices.cpp \
    eigen/test/prec_inverse_4x4.cpp \
    eigen/test/product_extra.cpp \
    eigen/test/product_large.cpp \
    eigen/test/product_mmtr.cpp \
    eigen/test/product_notemporary.cpp \
    eigen/test/product_selfadjoint.cpp \
    eigen/test/product_small.cpp \
    eigen/test/product_symm.cpp \
    eigen/test/product_syrk.cpp \
    eigen/test/product_trmm.cpp \
    eigen/test/product_trmv.cpp \
    eigen/test/product_trsolve.cpp \
    eigen/test/qr.cpp \
    eigen/test/qr_colpivoting.cpp \
    eigen/test/qr_fullpivoting.cpp \
    eigen/test/qtvector.cpp \
    eigen/test/real_qz.cpp \
    eigen/test/redux.cpp \
    eigen/test/ref.cpp \
    eigen/test/resize.cpp \
    eigen/test/rvalue_types.cpp \
    eigen/test/schur_complex.cpp \
    eigen/test/schur_real.cpp \
    eigen/test/selfadjoint.cpp \
    eigen/test/simplicial_cholesky.cpp \
    eigen/test/sizeof.cpp \
    eigen/test/sizeoverflow.cpp \
    eigen/test/smallvectors.cpp \
    eigen/test/sparse_basic.cpp \
    eigen/test/sparse_permutations.cpp \
    eigen/test/sparse_product.cpp \
    eigen/test/sparse_solvers.cpp \
    eigen/test/sparse_vector.cpp \
    eigen/test/sparseLM.cpp \
    eigen/test/sparselu.cpp \
    eigen/test/sparseqr.cpp \
    eigen/test/special_numbers.cpp \
    eigen/test/spqr_support.cpp \
    eigen/test/stable_norm.cpp \
    eigen/test/stddeque.cpp \
    eigen/test/stddeque_overload.cpp \
    eigen/test/stdlist.cpp \
    eigen/test/stdlist_overload.cpp \
    eigen/test/stdvector.cpp \
    eigen/test/stdvector_overload.cpp \
    eigen/test/superlu_support.cpp \
    eigen/test/swap.cpp \
    eigen/test/triangular.cpp \
    eigen/test/umeyama.cpp \
    eigen/test/umfpack_support.cpp \
    eigen/test/unalignedassert.cpp \
    eigen/test/unalignedcount.cpp \
    eigen/test/upperbidiagonalization.cpp \
    eigen/test/vectorization_logic.cpp \
    eigen/test/vectorwiseop.cpp \
    eigen/test/visitor.cpp \
    eigen/test/zerosized.cpp \
    eigen/unsupported/bench/bench_svd.cpp \
    eigen/unsupported/doc/examples/BVH_Example.cpp \
    eigen/unsupported/doc/examples/FFT.cpp \
    eigen/unsupported/doc/examples/MatrixExponential.cpp \
    eigen/unsupported/doc/examples/MatrixFunction.cpp \
    eigen/unsupported/doc/examples/MatrixLogarithm.cpp \
    eigen/unsupported/doc/examples/MatrixPower.cpp \
    eigen/unsupported/doc/examples/MatrixPower_optimal.cpp \
    eigen/unsupported/doc/examples/MatrixSine.cpp \
    eigen/unsupported/doc/examples/MatrixSinh.cpp \
    eigen/unsupported/doc/examples/MatrixSquareRoot.cpp \
    eigen/unsupported/doc/examples/PolynomialSolver1.cpp \
    eigen/unsupported/doc/examples/PolynomialUtils1.cpp \
    eigen/unsupported/test/alignedvector3.cpp \
    eigen/unsupported/test/autodiff.cpp \
    eigen/unsupported/test/bdcsvd.cpp \
    eigen/unsupported/test/BVH.cpp \
    eigen/unsupported/test/dgmres.cpp \
    eigen/unsupported/test/FFT.cpp \
    eigen/unsupported/test/FFTW.cpp \
    eigen/unsupported/test/forward_adolc.cpp \
    eigen/unsupported/test/gmres.cpp \
    eigen/unsupported/test/jacobisvd.cpp \
    eigen/unsupported/test/kronecker_product.cpp \
    eigen/unsupported/test/levenberg_marquardt.cpp \
    eigen/unsupported/test/matrix_exponential.cpp \
    eigen/unsupported/test/matrix_function.cpp \
    eigen/unsupported/test/matrix_power.cpp \
    eigen/unsupported/test/matrix_square_root.cpp \
    eigen/unsupported/test/minres.cpp \
    eigen/unsupported/test/mpreal_support.cpp \
    eigen/unsupported/test/NonLinearOptimization.cpp \
    eigen/unsupported/test/NumericalDiff.cpp \
    eigen/unsupported/test/openglsupport.cpp \
    eigen/unsupported/test/polynomialsolver.cpp \
    eigen/unsupported/test/polynomialutils.cpp \
    eigen/unsupported/test/sparse_extra.cpp \
    eigen/unsupported/test/splines.cpp \
    eigen/demos/mix_eigen_and_c/example.c

HEADERS  += mainwindow.h \
    player.h \
    circle.h \
    vector.h \
    point.h \
    gameitem.h \
    bonus.h \
    field.h \
    eigen/bench/btl/actions/action_aat_product.hh \
    eigen/bench/btl/actions/action_ata_product.hh \
    eigen/bench/btl/actions/action_atv_product.hh \
    eigen/bench/btl/actions/action_axpby.hh \
    eigen/bench/btl/actions/action_axpy.hh \
    eigen/bench/btl/actions/action_cholesky.hh \
    eigen/bench/btl/actions/action_ger.hh \
    eigen/bench/btl/actions/action_hessenberg.hh \
    eigen/bench/btl/actions/action_lu_decomp.hh \
    eigen/bench/btl/actions/action_lu_solve.hh \
    eigen/bench/btl/actions/action_matrix_matrix_product.hh \
    eigen/bench/btl/actions/action_matrix_matrix_product_bis.hh \
    eigen/bench/btl/actions/action_matrix_vector_product.hh \
    eigen/bench/btl/actions/action_partial_lu.hh \
    eigen/bench/btl/actions/action_rot.hh \
    eigen/bench/btl/actions/action_symv.hh \
    eigen/bench/btl/actions/action_syr2.hh \
    eigen/bench/btl/actions/action_trisolve.hh \
    eigen/bench/btl/actions/action_trisolve_matrix.hh \
    eigen/bench/btl/actions/action_trmm.hh \
    eigen/bench/btl/actions/basic_actions.hh \
    eigen/bench/btl/data/gnuplot_common_settings.hh \
    eigen/bench/btl/generic_bench/init/init_function.hh \
    eigen/bench/btl/generic_bench/init/init_matrix.hh \
    eigen/bench/btl/generic_bench/init/init_vector.hh \
    eigen/bench/btl/generic_bench/static/bench_static.hh \
    eigen/bench/btl/generic_bench/static/intel_bench_fixed_size.hh \
    eigen/bench/btl/generic_bench/static/static_size_generator.hh \
    eigen/bench/btl/generic_bench/timers/mixed_perf_analyzer.hh \
    eigen/bench/btl/generic_bench/timers/portable_perf_analyzer.hh \
    eigen/bench/btl/generic_bench/timers/portable_perf_analyzer_old.hh \
    eigen/bench/btl/generic_bench/timers/portable_timer.hh \
    eigen/bench/btl/generic_bench/timers/STL_perf_analyzer.hh \
    eigen/bench/btl/generic_bench/timers/STL_timer.hh \
    eigen/bench/btl/generic_bench/timers/x86_perf_analyzer.hh \
    eigen/bench/btl/generic_bench/timers/x86_timer.hh \
    eigen/bench/btl/generic_bench/utils/size_lin_log.hh \
    eigen/bench/btl/generic_bench/utils/size_log.hh \
    eigen/bench/btl/generic_bench/utils/utilities.h \
    eigen/bench/btl/generic_bench/utils/xy_file.hh \
    eigen/bench/btl/generic_bench/bench.hh \
    eigen/bench/btl/generic_bench/bench_parameter.hh \
    eigen/bench/btl/generic_bench/btl.hh \
    eigen/bench/btl/libs/BLAS/blas.h \
    eigen/bench/btl/libs/BLAS/blas_interface.hh \
    eigen/bench/btl/libs/BLAS/blas_interface_impl.hh \
    eigen/bench/btl/libs/BLAS/c_interface_base.h \
    eigen/bench/btl/libs/blitz/blitz_interface.hh \
    eigen/bench/btl/libs/blitz/blitz_LU_solve_interface.hh \
    eigen/bench/btl/libs/blitz/tiny_blitz_interface.hh \
    eigen/bench/btl/libs/eigen2/eigen2_interface.hh \
    eigen/bench/btl/libs/eigen3/eigen3_interface.hh \
    eigen/bench/btl/libs/gmm/gmm_interface.hh \
    eigen/bench/btl/libs/gmm/gmm_LU_solve_interface.hh \
    eigen/bench/btl/libs/mtl4/mtl4_interface.hh \
    eigen/bench/btl/libs/mtl4/mtl4_LU_solve_interface.hh \
    eigen/bench/btl/libs/STL/STL_interface.hh \
    eigen/bench/btl/libs/tvmet/tvmet_interface.hh \
    eigen/bench/btl/libs/ublas/ublas_interface.hh \
    eigen/bench/spbench/spbenchsolver.h \
    eigen/bench/spbench/spbenchstyle.h \
    eigen/bench/basicbenchmark.h \
    eigen/bench/BenchSparseUtil.h \
    eigen/bench/BenchTimer.h \
    eigen/bench/BenchUtil.h \
    eigen/blas/BandTriangularSolver.h \
    eigen/blas/common.h \
    eigen/blas/GeneralRank1Update.h \
    eigen/blas/level1_cplx_impl.h \
    eigen/blas/level1_impl.h \
    eigen/blas/level1_real_impl.h \
    eigen/blas/level2_cplx_impl.h \
    eigen/blas/level2_impl.h \
    eigen/blas/level2_real_impl.h \
    eigen/blas/level3_impl.h \
    eigen/blas/PackedSelfadjointProduct.h \
    eigen/blas/PackedTriangularMatrixVector.h \
    eigen/blas/PackedTriangularSolverVector.h \
    eigen/blas/Rank2Update.h \
    eigen/demos/mandelbrot/mandelbrot.h \
    eigen/demos/mix_eigen_and_c/binary_library.h \
    eigen/demos/opengl/camera.h \
    eigen/demos/opengl/gpuhelper.h \
    eigen/demos/opengl/icosphere.h \
    eigen/demos/opengl/quaternion_demo.h \
    eigen/demos/opengl/trackball.h \
    eigen/Eigen/src/Cholesky/LDLT.h \
    eigen/Eigen/src/Cholesky/LLT.h \
    eigen/Eigen/src/Cholesky/LLT_MKL.h \
    eigen/Eigen/src/CholmodSupport/CholmodSupport.h \
    eigen/Eigen/src/Core/arch/AltiVec/Complex.h \
    eigen/Eigen/src/Core/arch/AltiVec/PacketMath.h \
    eigen/Eigen/src/Core/arch/Default/Settings.h \
    eigen/Eigen/src/Core/arch/NEON/Complex.h \
    eigen/Eigen/src/Core/arch/NEON/PacketMath.h \
    eigen/Eigen/src/Core/arch/SSE/Complex.h \
    eigen/Eigen/src/Core/arch/SSE/MathFunctions.h \
    eigen/Eigen/src/Core/arch/SSE/PacketMath.h \
    eigen/Eigen/src/Core/products/CoeffBasedProduct.h \
    eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
    eigen/Eigen/src/Core/products/GeneralMatrixMatrix.h \
    eigen/Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
    eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
    eigen/Eigen/src/Core/products/GeneralMatrixVector.h \
    eigen/Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
    eigen/Eigen/src/Core/products/Parallelizer.h \
    eigen/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    eigen/Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
    eigen/Eigen/src/Core/products/SelfadjointMatrixVector.h \
    eigen/Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
    eigen/Eigen/src/Core/products/SelfadjointProduct.h \
    eigen/Eigen/src/Core/products/SelfadjointRank2Update.h \
    eigen/Eigen/src/Core/products/TriangularMatrixMatrix.h \
    eigen/Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
    eigen/Eigen/src/Core/products/TriangularMatrixVector.h \
    eigen/Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
    eigen/Eigen/src/Core/products/TriangularSolverMatrix.h \
    eigen/Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
    eigen/Eigen/src/Core/products/TriangularSolverVector.h \
    eigen/Eigen/src/Core/util/BlasUtil.h \
    eigen/Eigen/src/Core/util/Constants.h \
    eigen/Eigen/src/Core/util/DisableStupidWarnings.h \
    eigen/Eigen/src/Core/util/ForwardDeclarations.h \
    eigen/Eigen/src/Core/util/Macros.h \
    eigen/Eigen/src/Core/util/Memory.h \
    eigen/Eigen/src/Core/util/Meta.h \
    eigen/Eigen/src/Core/util/MKL_support.h \
    eigen/Eigen/src/Core/util/NonMPL2.h \
    eigen/Eigen/src/Core/util/ReenableStupidWarnings.h \
    eigen/Eigen/src/Core/util/StaticAssert.h \
    eigen/Eigen/src/Core/util/XprHelper.h \
    eigen/Eigen/src/Core/Array.h \
    eigen/Eigen/src/Core/ArrayBase.h \
    eigen/Eigen/src/Core/ArrayWrapper.h \
    eigen/Eigen/src/Core/Assign.h \
    eigen/Eigen/src/Core/Assign_MKL.h \
    eigen/Eigen/src/Core/BandMatrix.h \
    eigen/Eigen/src/Core/Block.h \
    eigen/Eigen/src/Core/BooleanRedux.h \
    eigen/Eigen/src/Core/CommaInitializer.h \
    eigen/Eigen/src/Core/CoreIterators.h \
    eigen/Eigen/src/Core/CwiseBinaryOp.h \
    eigen/Eigen/src/Core/CwiseNullaryOp.h \
    eigen/Eigen/src/Core/CwiseUnaryOp.h \
    eigen/Eigen/src/Core/CwiseUnaryView.h \
    eigen/Eigen/src/Core/DenseBase.h \
    eigen/Eigen/src/Core/DenseCoeffsBase.h \
    eigen/Eigen/src/Core/DenseStorage.h \
    eigen/Eigen/src/Core/Diagonal.h \
    eigen/Eigen/src/Core/DiagonalMatrix.h \
    eigen/Eigen/src/Core/DiagonalProduct.h \
    eigen/Eigen/src/Core/Dot.h \
    eigen/Eigen/src/Core/EigenBase.h \
    eigen/Eigen/src/Core/Flagged.h \
    eigen/Eigen/src/Core/ForceAlignedAccess.h \
    eigen/Eigen/src/Core/Functors.h \
    eigen/Eigen/src/Core/Fuzzy.h \
    eigen/Eigen/src/Core/GeneralProduct.h \
    eigen/Eigen/src/Core/GenericPacketMath.h \
    eigen/Eigen/src/Core/GlobalFunctions.h \
    eigen/Eigen/src/Core/IO.h \
    eigen/Eigen/src/Core/Map.h \
    eigen/Eigen/src/Core/MapBase.h \
    eigen/Eigen/src/Core/MathFunctions.h \
    eigen/Eigen/src/Core/Matrix.h \
    eigen/Eigen/src/Core/MatrixBase.h \
    eigen/Eigen/src/Core/NestByValue.h \
    eigen/Eigen/src/Core/NoAlias.h \
    eigen/Eigen/src/Core/NumTraits.h \
    eigen/Eigen/src/Core/PermutationMatrix.h \
    eigen/Eigen/src/Core/PlainObjectBase.h \
    eigen/Eigen/src/Core/ProductBase.h \
    eigen/Eigen/src/Core/Random.h \
    eigen/Eigen/src/Core/Redux.h \
    eigen/Eigen/src/Core/Ref.h \
    eigen/Eigen/src/Core/Replicate.h \
    eigen/Eigen/src/Core/ReturnByValue.h \
    eigen/Eigen/src/Core/Reverse.h \
    eigen/Eigen/src/Core/Select.h \
    eigen/Eigen/src/Core/SelfAdjointView.h \
    eigen/Eigen/src/Core/SelfCwiseBinaryOp.h \
    eigen/Eigen/src/Core/SolveTriangular.h \
    eigen/Eigen/src/Core/StableNorm.h \
    eigen/Eigen/src/Core/Stride.h \
    eigen/Eigen/src/Core/Swap.h \
    eigen/Eigen/src/Core/Transpose.h \
    eigen/Eigen/src/Core/Transpositions.h \
    eigen/Eigen/src/Core/TriangularMatrix.h \
    eigen/Eigen/src/Core/VectorBlock.h \
    eigen/Eigen/src/Core/VectorwiseOp.h \
    eigen/Eigen/src/Core/Visitor.h \
    eigen/Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
    eigen/Eigen/src/Eigen2Support/Geometry/All.h \
    eigen/Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
    eigen/Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Quaternion.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
    eigen/Eigen/src/Eigen2Support/Geometry/RotationBase.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Scaling.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Transform.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Translation.h \
    eigen/Eigen/src/Eigen2Support/Block.h \
    eigen/Eigen/src/Eigen2Support/Cwise.h \
    eigen/Eigen/src/Eigen2Support/CwiseOperators.h \
    eigen/Eigen/src/Eigen2Support/Lazy.h \
    eigen/Eigen/src/Eigen2Support/LeastSquares.h \
    eigen/Eigen/src/Eigen2Support/LU.h \
    eigen/Eigen/src/Eigen2Support/Macros.h \
    eigen/Eigen/src/Eigen2Support/MathFunctions.h \
    eigen/Eigen/src/Eigen2Support/Memory.h \
    eigen/Eigen/src/Eigen2Support/Meta.h \
    eigen/Eigen/src/Eigen2Support/Minor.h \
    eigen/Eigen/src/Eigen2Support/QR.h \
    eigen/Eigen/src/Eigen2Support/SVD.h \
    eigen/Eigen/src/Eigen2Support/TriangularSolver.h \
    eigen/Eigen/src/Eigen2Support/VectorBlock.h \
    eigen/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
    eigen/Eigen/src/Eigenvalues/ComplexSchur.h \
    eigen/Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
    eigen/Eigen/src/Eigenvalues/EigenSolver.h \
    eigen/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
    eigen/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    eigen/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
    eigen/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    eigen/Eigen/src/Eigenvalues/RealQZ.h \
    eigen/Eigen/src/Eigenvalues/RealSchur.h \
    eigen/Eigen/src/Eigenvalues/RealSchur_MKL.h \
    eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h \
    eigen/Eigen/src/Eigenvalues/Tridiagonalization.h \
    eigen/Eigen/src/Geometry/arch/Geometry_SSE.h \
    eigen/Eigen/src/Geometry/AlignedBox.h \
    eigen/Eigen/src/Geometry/AngleAxis.h \
    eigen/Eigen/src/Geometry/EulerAngles.h \
    eigen/Eigen/src/Geometry/Homogeneous.h \
    eigen/Eigen/src/Geometry/Hyperplane.h \
    eigen/Eigen/src/Geometry/OrthoMethods.h \
    eigen/Eigen/src/Geometry/ParametrizedLine.h \
    eigen/Eigen/src/Geometry/Quaternion.h \
    eigen/Eigen/src/Geometry/Rotation2D.h \
    eigen/Eigen/src/Geometry/RotationBase.h \
    eigen/Eigen/src/Geometry/Scaling.h \
    eigen/Eigen/src/Geometry/Transform.h \
    eigen/Eigen/src/Geometry/Translation.h \
    eigen/Eigen/src/Geometry/Umeyama.h \
    eigen/Eigen/src/Householder/BlockHouseholder.h \
    eigen/Eigen/src/Householder/Householder.h \
    eigen/Eigen/src/Householder/HouseholderSequence.h \
    eigen/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
    eigen/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
    eigen/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
    eigen/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
    eigen/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
    eigen/Eigen/src/Jacobi/Jacobi.h \
    eigen/Eigen/src/LU/arch/Inverse_SSE.h \
    eigen/Eigen/src/LU/Determinant.h \
    eigen/Eigen/src/LU/FullPivLU.h \
    eigen/Eigen/src/LU/Inverse.h \
    eigen/Eigen/src/LU/PartialPivLU.h \
    eigen/Eigen/src/LU/PartialPivLU_MKL.h \
    eigen/Eigen/src/MetisSupport/MetisSupport.h \
    eigen/Eigen/src/misc/blas.h \
    eigen/Eigen/src/misc/Image.h \
    eigen/Eigen/src/misc/Kernel.h \
    eigen/Eigen/src/misc/Solve.h \
    eigen/Eigen/src/misc/SparseSolve.h \
    eigen/Eigen/src/OrderingMethods/Amd.h \
    eigen/Eigen/src/OrderingMethods/Eigen_Colamd.h \
    eigen/Eigen/src/OrderingMethods/Ordering.h \
    eigen/Eigen/src/PardisoSupport/PardisoSupport.h \
    eigen/Eigen/src/PaStiXSupport/PaStiXSupport.h \
    eigen/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
    eigen/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
    eigen/Eigen/src/plugins/BlockMethods.h \
    eigen/Eigen/src/plugins/CommonCwiseBinaryOps.h \
    eigen/Eigen/src/plugins/CommonCwiseUnaryOps.h \
    eigen/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
    eigen/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
    eigen/Eigen/src/QR/ColPivHouseholderQR.h \
    eigen/Eigen/src/QR/ColPivHouseholderQR_MKL.h \
    eigen/Eigen/src/QR/FullPivHouseholderQR.h \
    eigen/Eigen/src/QR/HouseholderQR.h \
    eigen/Eigen/src/QR/HouseholderQR_MKL.h \
    eigen/Eigen/src/SparseCholesky/SimplicialCholesky.h \
    eigen/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
    eigen/Eigen/src/SparseCore/AmbiVector.h \
    eigen/Eigen/src/SparseCore/CompressedStorage.h \
    eigen/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
    eigen/Eigen/src/SparseCore/MappedSparseMatrix.h \
    eigen/Eigen/src/SparseCore/SparseBlock.h \
    eigen/Eigen/src/SparseCore/SparseColEtree.h \
    eigen/Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
    eigen/Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
    eigen/Eigen/src/SparseCore/SparseDenseProduct.h \
    eigen/Eigen/src/SparseCore/SparseDiagonalProduct.h \
    eigen/Eigen/src/SparseCore/SparseDot.h \
    eigen/Eigen/src/SparseCore/SparseFuzzy.h \
    eigen/Eigen/src/SparseCore/SparseMatrix.h \
    eigen/Eigen/src/SparseCore/SparseMatrixBase.h \
    eigen/Eigen/src/SparseCore/SparsePermutation.h \
    eigen/Eigen/src/SparseCore/SparseProduct.h \
    eigen/Eigen/src/SparseCore/SparseRedux.h \
    eigen/Eigen/src/SparseCore/SparseSelfAdjointView.h \
    eigen/Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
    eigen/Eigen/src/SparseCore/SparseTranspose.h \
    eigen/Eigen/src/SparseCore/SparseTriangularView.h \
    eigen/Eigen/src/SparseCore/SparseUtil.h \
    eigen/Eigen/src/SparseCore/SparseVector.h \
    eigen/Eigen/src/SparseCore/SparseView.h \
    eigen/Eigen/src/SparseCore/TriangularSolver.h \
    eigen/Eigen/src/SparseLU/SparseLU.h \
    eigen/Eigen/src/SparseLU/SparseLU_column_bmod.h \
    eigen/Eigen/src/SparseLU/SparseLU_column_dfs.h \
    eigen/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
    eigen/Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
    eigen/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
    eigen/Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
    eigen/Eigen/src/SparseLU/SparseLU_Memory.h \
    eigen/Eigen/src/SparseLU/SparseLU_panel_bmod.h \
    eigen/Eigen/src/SparseLU/SparseLU_panel_dfs.h \
    eigen/Eigen/src/SparseLU/SparseLU_pivotL.h \
    eigen/Eigen/src/SparseLU/SparseLU_pruneL.h \
    eigen/Eigen/src/SparseLU/SparseLU_relax_snode.h \
    eigen/Eigen/src/SparseLU/SparseLU_Structs.h \
    eigen/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
    eigen/Eigen/src/SparseLU/SparseLU_Utils.h \
    eigen/Eigen/src/SparseLU/SparseLUImpl.h \
    eigen/Eigen/src/SparseQR/SparseQR.h \
    eigen/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
    eigen/Eigen/src/StlSupport/details.h \
    eigen/Eigen/src/StlSupport/StdDeque.h \
    eigen/Eigen/src/StlSupport/StdList.h \
    eigen/Eigen/src/StlSupport/StdVector.h \
    eigen/Eigen/src/SuperLUSupport/SuperLUSupport.h \
    eigen/Eigen/src/SVD/JacobiSVD.h \
    eigen/Eigen/src/SVD/JacobiSVD_MKL.h \
    eigen/Eigen/src/SVD/UpperBidiagonalization.h \
    eigen/Eigen/src/UmfPackSupport/UmfPackSupport.h \
    eigen/lapack/lapack_common.h \
    eigen/test/eigen2/gsl_helper.h \
    eigen/test/eigen2/main.h \
    eigen/test/eigen2/product.h \
    eigen/test/eigen2/sparse.h \
    eigen/test/main.h \
    eigen/test/product.h \
    eigen/test/sparse.h \
    eigen/test/sparse_solver.h \
    eigen/unsupported/Eigen/src/AutoDiff/AutoDiffJacobian.h \
    eigen/unsupported/Eigen/src/AutoDiff/AutoDiffScalar.h \
    eigen/unsupported/Eigen/src/AutoDiff/AutoDiffVector.h \
    eigen/unsupported/Eigen/src/BVH/BVAlgorithms.h \
    eigen/unsupported/Eigen/src/BVH/KdBVH.h \
    eigen/unsupported/Eigen/src/Eigenvalues/ArpackSelfAdjointEigenSolver.h \
    eigen/unsupported/Eigen/src/FFT/ei_fftw_impl.h \
    eigen/unsupported/Eigen/src/FFT/ei_kissfft_impl.h \
    eigen/unsupported/Eigen/src/IterativeSolvers/ConstrainedConjGrad.h \
    eigen/unsupported/Eigen/src/IterativeSolvers/DGMRES.h \
    eigen/unsupported/Eigen/src/IterativeSolvers/GMRES.h \
    eigen/unsupported/Eigen/src/IterativeSolvers/IncompleteCholesky.h \
    eigen/unsupported/Eigen/src/IterativeSolvers/IncompleteLU.h \
    eigen/unsupported/Eigen/src/IterativeSolvers/IterationController.h \
    eigen/unsupported/Eigen/src/IterativeSolvers/MINRES.h \
    eigen/unsupported/Eigen/src/IterativeSolvers/Scaling.h \
    eigen/unsupported/Eigen/src/KroneckerProduct/KroneckerTensorProduct.h \
    eigen/unsupported/Eigen/src/LevenbergMarquardt/LevenbergMarquardt.h \
    eigen/unsupported/Eigen/src/LevenbergMarquardt/LMcovar.h \
    eigen/unsupported/Eigen/src/LevenbergMarquardt/LMonestep.h \
    eigen/unsupported/Eigen/src/LevenbergMarquardt/LMpar.h \
    eigen/unsupported/Eigen/src/LevenbergMarquardt/LMqrsolv.h \
    eigen/unsupported/Eigen/src/MatrixFunctions/MatrixExponential.h \
    eigen/unsupported/Eigen/src/MatrixFunctions/MatrixFunction.h \
    eigen/unsupported/Eigen/src/MatrixFunctions/MatrixFunctionAtomic.h \
    eigen/unsupported/Eigen/src/MatrixFunctions/MatrixLogarithm.h \
    eigen/unsupported/Eigen/src/MatrixFunctions/MatrixPower.h \
    eigen/unsupported/Eigen/src/MatrixFunctions/MatrixSquareRoot.h \
    eigen/unsupported/Eigen/src/MatrixFunctions/StemFunction.h \
    eigen/unsupported/Eigen/src/MoreVectorization/MathFunctions.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/chkder.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/covar.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/dogleg.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/fdjac1.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/HybridNonLinearSolver.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/LevenbergMarquardt.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/lmpar.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/qrsolv.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/r1mpyq.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/r1updt.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/rwupdt.h \
    eigen/unsupported/Eigen/src/NumericalDiff/NumericalDiff.h \
    eigen/unsupported/Eigen/src/Polynomials/Companion.h \
    eigen/unsupported/Eigen/src/Polynomials/PolynomialSolver.h \
    eigen/unsupported/Eigen/src/Polynomials/PolynomialUtils.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineInplaceLU.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineMatrix.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineMatrixBase.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineProduct.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineStorage.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineUtil.h \
    eigen/unsupported/Eigen/src/SparseExtra/BlockOfDynamicSparseMatrix.h \
    eigen/unsupported/Eigen/src/SparseExtra/DynamicSparseMatrix.h \
    eigen/unsupported/Eigen/src/SparseExtra/MarketIO.h \
    eigen/unsupported/Eigen/src/SparseExtra/MatrixMarketIterator.h \
    eigen/unsupported/Eigen/src/SparseExtra/RandomSetter.h \
    eigen/unsupported/Eigen/src/Splines/Spline.h \
    eigen/unsupported/Eigen/src/Splines/SplineFitting.h \
    eigen/unsupported/Eigen/src/Splines/SplineFwd.h \
    eigen/unsupported/Eigen/src/SVD/BDCSVD.h \
    eigen/unsupported/Eigen/src/SVD/JacobiSVD.h \
    eigen/unsupported/Eigen/src/SVD/SVDBase.h \
    eigen/unsupported/test/mpreal/mpreal.h \
    eigen/unsupported/test/matrix_functions.h \
    eigen/unsupported/test/svd_common.h \
    eigen/Eigen/Dense

FORMS    += mainwindow.ui
